// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX7H3dW6IYlAsfyRfI1I9fCgrpZj9TVy4',
    appId: '1:590040721290:web:0dc23ea6c1b32fa1ccca73',
    messagingSenderId: '590040721290',
    projectId: 'gezgor10-14b48',
    authDomain: 'gezgor10-14b48.firebaseapp.com',
    storageBucket: 'gezgor10-14b48.firebasestorage.app',
    measurementId: 'G-CDDZGZYVLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5F0FcURd1aK06xy9Kejl0GXwndgapgR0',
    appId: '1:590040721290:android:67ff07f3cef9d41bccca73',
    messagingSenderId: '590040721290',
    projectId: 'gezgor10-14b48',
    storageBucket: 'gezgor10-14b48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFD5kE8azx8eTqGnt2xYhzvhGZr1cGBD8',
    appId: '1:590040721290:ios:3bb05f434aa97676ccca73',
    messagingSenderId: '590040721290',
    projectId: 'gezgor10-14b48',
    storageBucket: 'gezgor10-14b48.firebasestorage.app',
    iosBundleId: 'com.example.gezgor10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFD5kE8azx8eTqGnt2xYhzvhGZr1cGBD8',
    appId: '1:590040721290:ios:3bb05f434aa97676ccca73',
    messagingSenderId: '590040721290',
    projectId: 'gezgor10-14b48',
    storageBucket: 'gezgor10-14b48.firebasestorage.app',
    iosBundleId: 'com.example.gezgor10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX7H3dW6IYlAsfyRfI1I9fCgrpZj9TVy4',
    appId: '1:590040721290:web:767d0c253618d5ccccca73',
    messagingSenderId: '590040721290',
    projectId: 'gezgor10-14b48',
    authDomain: 'gezgor10-14b48.firebaseapp.com',
    storageBucket: 'gezgor10-14b48.firebasestorage.app',
    measurementId: 'G-CJ2MRPTYJJ',
  );
}
